/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;
import Entidades.Carro;
import DaoClass.DaoCarro;
/**
 *
 * @author Cliente
 * 
 * 
 */
public class CadastrarProduto extends javax.swing.JFrame {

    
    /**
     * Creates new form CadastrarProdutro
     */
    public CadastrarProduto() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TelaCadastro = new javax.swing.JTabbedPane();
        painel_cadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ano_Frab_prod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cor_prod = new javax.swing.JTextField();
        Nome_prod = new javax.swing.JTextField();
        Fabricante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Chassi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Valor_prod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Qdt_esto_PRod = new javax.swing.JTextField();
        BT_salvar_Cad_Prod = new javax.swing.JButton();
        Bt_Cancelar_Cad_Prod = new javax.swing.JButton();
        Bt_Limpar_Cad_Prod = new javax.swing.JButton();
        TelaAlteracao = new javax.swing.JTabbedPane();
        painel_cadastro1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Ano_Frab_prod1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Cor_prod1 = new javax.swing.JTextField();
        Nome_prod1 = new javax.swing.JTextField();
        Fabricante1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Chassi1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Valor_prod1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Qdt_esto_PRod1 = new javax.swing.JTextField();
        bt_alter_alter = new javax.swing.JButton();
        Bt_Cancelar_Cad_Prod1 = new javax.swing.JButton();
        Bt_Limpar_Cad_Prod1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        codigo_prod_alter = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nome_carro_buscar = new javax.swing.JTextField();
        bt_alt_buscar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nome do Produto:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Fabricante:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Ano de Fabricação:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Cor do Produto:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Numero do Chassi: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Valor do Produto:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Quantidade em Estoque");

        BT_salvar_Cad_Prod.setText("Salvar");
        BT_salvar_Cad_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_salvar_Cad_ProdActionPerformed(evt);
            }
        });

        Bt_Cancelar_Cad_Prod.setText("Cancelar");
        Bt_Cancelar_Cad_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cancelar_Cad_ProdActionPerformed(evt);
            }
        });

        Bt_Limpar_Cad_Prod.setText("Limpar");
        Bt_Limpar_Cad_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Limpar_Cad_ProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_cadastroLayout = new javax.swing.GroupLayout(painel_cadastro);
        painel_cadastro.setLayout(painel_cadastroLayout);
        painel_cadastroLayout.setHorizontalGroup(
            painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_cadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(painel_cadastroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Cor_prod)
                        .addGap(333, 333, 333))
                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                        .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_cadastroLayout.createSequentialGroup()
                                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(painel_cadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Fabricante))
                                        .addGroup(painel_cadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Nome_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ano_Frab_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_cadastroLayout.createSequentialGroup()
                                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Valor_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(BT_salvar_Cad_Prod)
                                        .addGap(18, 18, 18)
                                        .addComponent(Bt_Cancelar_Cad_Prod)))
                                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Qdt_esto_PRod, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_cadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Bt_Limpar_Cad_Prod)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painel_cadastroLayout.setVerticalGroup(
            painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cadastroLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nome_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Chassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Ano_Frab_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cor_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Valor_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Qdt_esto_PRod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(painel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_salvar_Cad_Prod)
                    .addComponent(Bt_Cancelar_Cad_Prod)
                    .addComponent(Bt_Limpar_Cad_Prod))
                .addGap(63, 63, 63))
        );

        TelaCadastro.addTab("", painel_cadastro);

        jTabbedPane1.addTab("Cadastrar Novo", TelaCadastro);

        TelaAlteracao.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Nome do Produto:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Fabricante:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Ano de Fabricação:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Cor do Produto:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Numero do Chassi: ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Valor do Produto:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Quantidade em Estoque");

        bt_alter_alter.setText("Alterar");
        bt_alter_alter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alter_alterActionPerformed(evt);
            }
        });

        Bt_Cancelar_Cad_Prod1.setText("Cancelar");
        Bt_Cancelar_Cad_Prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cancelar_Cad_Prod1ActionPerformed(evt);
            }
        });

        Bt_Limpar_Cad_Prod1.setText("Excluir");
        Bt_Limpar_Cad_Prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Limpar_Cad_Prod1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Codigo do Produto:");

        codigo_prod_alter.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        codigo_prod_alter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_prod_alterActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Nome do Produto:");

        nome_carro_buscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nome_carro_buscar.setToolTipText("Digite o nome do produto a ser buscado");

        bt_alt_buscar.setText("Buscar");
        bt_alt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_cadastro1Layout = new javax.swing.GroupLayout(painel_cadastro1);
        painel_cadastro1.setLayout(painel_cadastro1Layout);
        painel_cadastro1Layout.setHorizontalGroup(
            painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cadastro1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_cadastro1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painel_cadastro1Layout.createSequentialGroup()
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(codigo_prod_alter, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Nome_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nome_carro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56)
                                    .addComponent(bt_alt_buscar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_cadastro1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(bt_alter_alter)
                                .addGap(60, 60, 60)
                                .addComponent(Bt_Cancelar_Cad_Prod1)
                                .addGap(69, 69, 69)
                                .addComponent(Bt_Limpar_Cad_Prod1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_cadastro1Layout.createSequentialGroup()
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chassi1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(Valor_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(Ano_Frab_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cor_prod1)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Qdt_esto_PRod1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
            .addGroup(painel_cadastro1Layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        painel_cadastro1Layout.setVerticalGroup(
            painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cadastro1Layout.createSequentialGroup()
                .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_cadastro1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(nome_carro_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_alt_buscar))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel8)
                            .addComponent(Nome_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo_prod_alter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_cadastro1Layout.createSequentialGroup()
                                .addComponent(Fabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_cadastro1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Chassi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(Ano_Frab_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Cor_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_cadastro1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Qdt_esto_PRod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Valor_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(painel_cadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_alter_alter)
                    .addComponent(Bt_Cancelar_Cad_Prod1)
                    .addComponent(Bt_Limpar_Cad_Prod1))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        TelaAlteracao.addTab("", painel_cadastro1);

        jTabbedPane1.addTab("Alterar/ Excluir", TelaAlteracao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_salvar_Cad_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_salvar_Cad_ProdActionPerformed
        
        Carro carro = new Carro();
       
        carro.setNome(Nome_prod.getText()); 
        carro.setCor(Cor_prod.getText());
        carro.setFabric(Fabricante.getText());
        carro.setChassi(Chassi.getText());
        carro.setValor(Double.parseDouble(Valor_prod.getText()));
        carro.setAnoFabric(Integer.parseInt(Ano_Frab_prod.getText()));
        carro.setQdtEstoque(Integer.parseInt(Qdt_esto_PRod.getText()));
        
        DaoCarro dcarro = new DaoCarro();
        dcarro.inserir(carro);
        

        
        
    }//GEN-LAST:event_BT_salvar_Cad_ProdActionPerformed

    private void Bt_Cancelar_Cad_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cancelar_Cad_ProdActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_Bt_Cancelar_Cad_ProdActionPerformed

    private void Bt_Limpar_Cad_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Limpar_Cad_ProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Limpar_Cad_ProdActionPerformed

    private void bt_alter_alterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alter_alterActionPerformed
        // 
        Carro carro = new Carro(); 
       
        carro.setNome(Nome_prod.getText()); 
        carro.setCor(Cor_prod.getText());
        carro.setFabric(Fabricante.getText());
        carro.setChassi(Chassi.getText());
        carro.setValor(Double.parseDouble(Valor_prod.getText()));
        carro.setAnoFabric(Integer.parseInt(Ano_Frab_prod.getText()));
        carro.setQdtEstoque(Integer.parseInt(Qdt_esto_PRod.getText()));
        carro.setId_carro(Integer.parseInt(codigo_prod_alter.getText()));
               
        DaoCarro dcarro = new DaoCarro();
        dcarro.alterar(carro);
                
    }//GEN-LAST:event_bt_alter_alterActionPerformed

    private void Bt_Cancelar_Cad_Prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cancelar_Cad_Prod1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Bt_Cancelar_Cad_Prod1ActionPerformed

    private void Bt_Limpar_Cad_Prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Limpar_Cad_Prod1ActionPerformed
        
        Carro carro = new Carro();
        carro.setId_carro(Integer.parseInt(codigo_prod_alter.getText()));
        carro.setNome(Nome_prod.getText());
        
        DaoCarro dcarro = new DaoCarro();
        dcarro.excluir(carro);
        
        
    }//GEN-LAST:event_Bt_Limpar_Cad_Prod1ActionPerformed

    private void bt_alt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alt_buscarActionPerformed
        
        DaoCarro dcarro = new DaoCarro();
        
        Carro carro = dcarro.consultar(nome_carro_buscar.getText());
        
        Nome_prod1.setText(carro.getNome());
        Cor_prod1.setText(carro.getCor());
        Fabricante1.setText(carro.getFabric());
        Chassi1.setText(carro.getChassi());
        Valor_prod1.setText(""+carro.getValor()+"");
        Ano_Frab_prod1.setText(""+ carro.getAnoFabric()+"");
        Qdt_esto_PRod1.setText(""+carro.getQdtEstoque()+"");
        codigo_prod_alter.setText(""+carro.getId_carro()+"");
       
        
        
    }//GEN-LAST:event_bt_alt_buscarActionPerformed

    private void codigo_prod_alterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_prod_alterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_prod_alterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ano_Frab_prod;
    private javax.swing.JTextField Ano_Frab_prod1;
    private javax.swing.JButton BT_salvar_Cad_Prod;
    private javax.swing.JButton Bt_Cancelar_Cad_Prod;
    private javax.swing.JButton Bt_Cancelar_Cad_Prod1;
    private javax.swing.JButton Bt_Limpar_Cad_Prod;
    private javax.swing.JButton Bt_Limpar_Cad_Prod1;
    private javax.swing.JTextField Chassi;
    private javax.swing.JTextField Chassi1;
    private javax.swing.JTextField Cor_prod;
    private javax.swing.JTextField Cor_prod1;
    private javax.swing.JTextField Fabricante;
    private javax.swing.JTextField Fabricante1;
    private javax.swing.JTextField Nome_prod;
    private javax.swing.JTextField Nome_prod1;
    private javax.swing.JTextField Qdt_esto_PRod;
    private javax.swing.JTextField Qdt_esto_PRod1;
    private javax.swing.JTabbedPane TelaAlteracao;
    private javax.swing.JTabbedPane TelaCadastro;
    private javax.swing.JTextField Valor_prod;
    private javax.swing.JTextField Valor_prod1;
    private javax.swing.JButton bt_alt_buscar;
    private javax.swing.JButton bt_alter_alter;
    private javax.swing.JTextField codigo_prod_alter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nome_carro_buscar;
    private javax.swing.JPanel painel_cadastro;
    private javax.swing.JPanel painel_cadastro1;
    // End of variables declaration//GEN-END:variables
}
